### ISSUE TITLE
Sliders dosen't work on firefox

### ISSUE THREAD

**Issue by the-glu** [agepoly/wish#30]
![https://i.imgur.com/rMdfhlF.png](https://i.imgur.com/rMdfhlF.png)

Sadness :(

**Comment by mariogeiger** [comment]
![screenshot from 2016-12-20 15-38-28](https://cloud.githubusercontent.com/assets/333780/21354459/788aa330-c6ca-11e6-9724-13b5ab67c4ac.png)

It works on my Firefox.
It should work because it's simply a `<input type="range"></input>`.

**Comment by the-glu** [comment]
Yes, seems to be an issue with my firefox (maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1278108 ? ), a simple page with a range input also doesn't works.
