### ISSUE TITLE
Result saving

### ISSUE THREAD

**Issue by iMhack** [agepoly/wish#32]
The result that are send to the participants are lost for the admin if he didn't manually copy pasted the solution of the problem.
The overall result should be send to the admin email address when the button is pressed to send to the participants.

**Comment by iMhack** [comment]
I might have an idea to make it simple and transparent.
When "Send results" is pressed, the solution is not computed if  "Update assignation" is not pressed would be a nice solution, right ?

**Comment by mariogeiger** [comment]
I think that it's already the case. I just have to send something to the admin.
