### ISSUE TITLE
Save and send mails

### ISSUE THREAD

**Issue by iMhack** [agepoly/wish#33]
Ne pas afficher "save and send mails" si il n'y a pas de mail qui sera envoyé.

**Comment by iMhack** [comment]
Suggestion : un popup si il y a un mail à envoyer.

**Comment by iMhack** [comment]
Suggestion : un popup si il y a un mail à envoyer.

**Comment by iMhack** [comment]
Suggestion : un popup si il y a un mail à envoyer.

**Comment by iMhack** [comment]
Suggestion : un popup si il y a un mail à envoyer.

**Comment by iMhack** [comment]
Suggestion : un popup si il y a un mail à envoyer.

**Comment by mariogeiger** [comment]
fixed in 9b8b99f6007e13463cf6d4b893332f11b56fd191
