### ISSUE TITLE
database is slow

### ISSUE THREAD

**Issue by mariogeiger** [agepoly/wish#37]

**Comment by iMhack** [comment]
Ah ouais, Is it coming from host or from recent changes ?

**Comment by mariogeiger** [comment]
J'imagine que c'est dû à l'accumulation des événements. Mais pas sûr du tout

**Comment by iMhack** [comment]
On arrive pas à charger l'historique :-/

**Comment by mariogeiger** [comment]
C'est lent que sur le smartphone, donc qui à voir avec la base de donnée.
A terme ca vaudrait quand meme la peine de passer à une base de donnée plus main stream comme mongodb.
